- name: Copy Over Stage Retrieval Script
  template: src=get_stage.sh dest=/mnt/gentoo/ mode=755

- name: Download Stage3 Tarball
  command: /mnt/gentoo/get_stage.sh chdir=/mnt/gentoo
  tags:
    - filesystem

- name: Unarchive Stage3 Tarball
  command: tar xapf stage3.xz
  args:
      creates: /mnt/gentoo/etc
      chdir: /mnt/gentoo/
  tags:
    - filesystem

- name: proc bind mounts
  command: mount -t proc proc /mnt/gentoo/proc
  tags:
    - filesystem

- name: dev bind mounts
  command: mount --rbind /dev /mnt/gentoo/dev
  tags:
    - filesystem

- name: sys bind mounts
  command: mount --rbind /sys /mnt/gentoo/sys
  tags:
    - filesystem

- name: Cleanup Stage3 Archive
  file: path=/mnt/gentoo/stage3.xz state=absent

- name: Cleanup get_stage.sh
  file: path=/mnt/gentoo/get_stage.sh state=absent

- name: copy resolv.conf
  command: cp -L /etc/resolv.conf /mnt/gentoo/etc/ creates=/mnt/gentoo/etc/resolv.conf

- name: set zoneinfo
  command: chroot /mnt/gentoo bash -c 'cp /usr/share/zoneinfo/{{ timezone }} /etc/localtime; echo "{{ timezone }}" > /etc/timezone'
  tags:
    - chroot

- name: Configure Hosts File
  template: src=hosts dest=/mnt/gentoo/etc/hosts

- name: Set Hostname
  template: src=hostname dest=/mnt/gentoo/etc/conf.d/hostname

- name: Configure Fstab
  copy: src=fstab dest=/mnt/gentoo/etc/fstab

- name: Initial emerge sync
  command: chroot /mnt/gentoo bash -c 'source /etc/profile;emerge --sync' creates=/mnt/gentoo/var/db/repos/gentoo/Manifest

- file:
    path: /tmp/chroot_completed
    state: touch
